### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tsalo** [tsalo/athena-web#2]
I'm currently using the NBCLab logo. If there isn't an ATHENA logo, I would combine the NBCLab one with the IGILab one for the project, if there is one.

**Comment by tsalo** [comment]
What about a brain-shaped wordcloud of CogPO terms? Per @mriedel56

**Comment by tsalo** [comment]
We may propose general design ideas and then outsource to a paid service.

**Comment by mriedel56** [comment]
What about this for the word cloud?

https://github.com/amueller/word_cloud

**Comment by tsalo** [comment]
I've added @mriedel56's word cloud to the site, though we're going to add in another one at a later date.
